Repository hmcts/rpx-xui-terms-and-conditions, pull requests merged in 2019-12, with the labels that each got.

#106 Feature/tests around db
  server/api/controllers/health/healthController.ts
  server/api/services/dbWrapper.ts
  server/common/interceptors.spec.ts
  server/database/index.ts
  server/database/repos/TCAppRepository.ts
  server/database/repos/TCAppRespository.spec.ts
  server/database/repos/TCDocumentRepository.spec.ts
  server/database/repos/TCUserAgreementRespository.spec.ts
  server/database/scripts/create_db.ts
  test/health.controller.spec.ts
Labels: ns:xui-terms-and-conditions-pr-106

#107 Feature/eui 1148 error handling
  charts/xui-terms-and-conditions/values.preview.template.yaml
  jest.config.js
  package.json
  server/api/controllers/apps/appsController.ts
  server/api/controllers/apps/router.ts
  server/api/controllers/documentManagement/documentManagement.controller.spec.ts
  server/api/controllers/documentManagement/documentManagementController.ts
  server/api/controllers/documentManagement/router.ts
  server/api/controllers/health/healthController.ts
  server/api/controllers/users/router.ts
  server/api/controllers/users/userController.ts
  server/api/errors/applicationError.ts
  server/api/errors/appsNotFoundError.ts
  server/api/errors/documentNotFoundError.ts
  server/api/errors/index.ts
  server/api/errors/invalidBearerTokenError.ts
  server/api/errors/invalidClientError.ts
  server/api/errors/invalidDBConnectionError.ts
  server/api/errors/invalidS2STokenError.ts
  server/api/errors/invalidUserError.ts
  server/api/middlewares/error.handler.ts
  server/api/middlewares/index.ts
  server/api/middlewares/validateAppVersion.ts
  server/api/middlewares/validateBearerToken.spec.ts
  server/api/middlewares/validateBearerToken.ts
  server/api/middlewares/validateClientSecurity.ts
  server/api/middlewares/validateDBConnection.ts
  server/api/middlewares/validateS2Stoken.ts
  server/api/services/apps.service.ts
  server/api/services/dbWrapper.ts
  server/api/services/documentManagement.service.ts
  server/api/services/s2sTokenValidation.service.ts
  server/api/services/userTokenValidation.service.ts
  server/api/services/users.service.ts
  server/common/interceptors.spec.ts
  server/common/server.ts
  server/common/swagger.ts
  server/database/index.ts
  server/database/scripts/create_db.ts
  server/database/sql/TCDocumentApp/create.sql
  server/database/sql/index.ts
  server/index.ts
  server/routes.ts
  test/apps.Controller.spec.ts
  test/health.controller.spec.ts
  test/s2sTokenValidation.service.spec.ts
  test/userTokenValidation.service.spec.ts
  test/users.controller.spec.ts
Labels: ns:xui-terms-and-conditions-pr-107

#109 added docker-compose and testing command on PR envs
  Dockerfile
  build.ts
  charts/xui-terms-and-conditions/values.preview.template.yaml
  docker-compose.yml
  docker.env
  package.json
  server/database/index.ts
  server/database/migrations/00001_create-initial-tables.sql
  server/database/migrations/00002_alter-initial-tables.sql
  server/database/migrations/00003_initial-seeded-data.js
  server/database/resources/terms.html
  server/database/scripts/create_db.ts
  server/database/scripts/migrate.ts
  wait-for
  yarn.lock
Labels: ns:xui-terms-and-conditions-pr-109

#111 test migration inside CNP file
  Jenkinsfile_CNP
  yarn.lock
Labels: ns:xui-terms-and-conditions-pr-111

#112 develop to master
  Jenkinsfile_CNP
  yarn.lock
Labels: ns:xui-terms-and-conditions-pr-112

#113 test migration inside CNP file
  Jenkinsfile_CNP
  docker-compose.yml
  server/database/migrations/00004_change_user_id_to_varchar.sql
Labels: ns:xui-terms-and-conditions-pr-113

#115 Feature/eui 1255 appinsights
  config/custom-environment-variables.yaml
  config/default.yaml
  package.json
  server/appInsights.ts
  server/common/server.ts
  yarn.lock
Labels: ns:xui-terms-and-conditions-pr-115

#116 Merge Uday App Insight to master
  config/custom-environment-variables.yaml
  config/default.yaml
  package.json
  server/appInsights.ts
  server/common/server.ts
  yarn.lock
Labels: ns:xui-terms-and-conditions-pr-116
